/**
 * Test script: generate a quote PDF using pdfmake.
 * Run: node scripts/test-pdf.mjs
 * Output: static/test-quote.pdf
 */

import path from 'node:path';
import fs from 'node:fs';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const projectRoot = path.join(__dirname, '..');

async function run() {
	const pdfmake = (await import('pdfmake')).default;

	const fontsDir = path.join(projectRoot, 'node_modules', 'pdfmake', 'fonts');
	const fonts = {
		Roboto: {
			normal: path.join(fontsDir, 'Roboto', 'Roboto-Regular.ttf'),
			bold: path.join(fontsDir, 'Roboto', 'Roboto-Medium.ttf'),
			italics: path.join(fontsDir, 'Roboto', 'Roboto-Italic.ttf'),
			bolditalics: path.join(fontsDir, 'Roboto', 'Roboto-MediumItalic.ttf')
		}
	};
	pdfmake.setFonts(fonts);

	const docDefinition = {
		pageSize: 'A4',
		pageMargins: [36, 36],
		content: [
			{ text: 'Test Quote PDF', style: 'header' },
			{ text: 'Generated by pdfmake (no Chromium)', fontSize: 10, margin: [0, 8, 0, 0] },
			{ text: '\nCustomer: Test User', fontSize: 10 },
			{ text: 'Email: test@example.com', fontSize: 10 },
			{ text: 'Roof: 200 m²', fontSize: 10 },
			{ text: '\nSubtotal: $10,000.00', fontSize: 10 },
			{ text: 'GST (10%): $1,000.00', fontSize: 10 },
			{ text: 'Total: $11,000.00', fontSize: 12, bold: true, margin: [0, 4, 0, 0] },
			{ text: '\nThank you for your interest!', fontSize: 9, margin: [0, 16, 0, 0] }
		],
		styles: { header: { fontSize: 18, bold: true, color: '#2e7d32' } }
	};

	const pdfDoc = pdfmake.createPdf(docDefinition);
	const buffer = await pdfDoc.getBuffer();

	const outPath = path.join(projectRoot, 'static', 'test-quote.pdf');
	fs.writeFileSync(outPath, buffer);
	console.log('✓ PDF generated:', outPath);
}

run().catch((e) => {
	console.error('PDF generation failed:', e);
	process.exit(1);
});
